### ISSUE TITLE
List all deployments

### ISSUE THREAD

**Issue by ohnorobo** [codeforamerica/CutePets#1]
To add to the map

**Comment by boonrs** [comment]
Twitter accounts listed here but not yet on the map:
* [Austin](https://twitter.com/cutepetsaustin), -97.7534014, 30.3077609
* [Portsmouth](https://twitter.com/CutePetsPtown),-76.3558621, 36.8685605
* [Denver](https://twitter.com/CutePetsDenver), -104.8551114, 39.7643389 <---- How could we miss this one, lol
